sudo: false
language: node_js
node_js:
  - "9"
  - "10"

matrix:
  fast_finish: true
  include:
    - node_js: "node"

cache:
  yarn: true

install:
  - yarn install

script:
  - yarn lint
  - yarn test:unit
  - yarn test:cov
